### PR TITLE
feat: add support for virtual can

### PR DESCRIPTION
**Pull request by ardrabczyk**
I'm going to use it like that in an algorithm for auto-detecting CAN speed (I also need listen-only mode for that https://github.com/einride/can-go/pull/174):

    canInfo, err := d.Info()
    if err != nil {
            return err
    }

    if canInfo.Type == candevice.VcanLinkType {
            log.Println("Type is vcan, cancel auto-detecting CAN speed")
            return nil
    }

SetBitrate() and others don't have to changed, they will return `netlink receive: operation not supported` errors. Receive() and TransmitFrame() will continue working without any changes.

There are no tests, I thought I could add them to pkg/candevice/device_integration_test.go but nothing there uses vcan0 at this moment.

### CODE REVIEW

**Comment by Edholm** [comment]
Please have a look at the failing CI

**Comment by ardrabczyk** [comment]
yeah I know that [tests fail](https://github.com/einride/can-go/pull/197#issuecomment-1707978909) but IMO it should be fixed elsewhere because all builds fail since Sep 4 https://github.com/einride/can-go/actions and by the time when I pushed this PR they were already failing.

**Comment by Edholm** [comment]
Yeah I noticed after I wrote. I will take a look. I suspect it is due to the Go version having been bumped to 1.21 :)

**Comment by Edholm** [comment]
Should be fixed now. You can rebase on master :)

**Pull request closed without merging**
